-- Here are some of the exercises for which you can write SQL queries to self evaluate using all the concepts we have learnt to write SQL Queries.
-- * All the exercises are based on retail tables.
-- * We have already setup the tables and also populated the data.
-- * We will use all the 6 tables in retail database as part of these exercises.

-- Here are the commands to validate the tables
SELECT count(*) FROM departments;
SELECT count(*) FROM categories;
SELECT count(*) FROM products;
SELECT count(*) FROM orders;
SELECT count(*) FROM order_items;
SELECT count(*) FROM customers;

-- ### Exercise 1 - Customer order count

-- Get order count per customer for the month of 2014 January.

-- * Tables - `orders` and `customers`
-- * Data should be sorted in descending order by count and ascending order by customer id.
-- * Output should contain `customer_id`, `customer_fname`, `customer_lname` and `customer_order_count`.

SELECT c.customer_id, 
		c.customer_fname, 
		c.customer_lname, 
		count(o.order_id) AS customer_order_count
FROM orders AS o
	JOIN customers AS c
		ON o.order_customer_id = c.customer_id
WHERE to_char(o.order_date::timestamp, 'yyyy-MM') = '2014-01'
GROUP BY 1
ORDER BY 4 DESC;


-- ### Exercise 2 - Dormant Customers

-- Get the customer details who have not placed any order for the month of 2014 January.
-- * Tables - `orders` and `customers`
-- * Output Columns - **All columns from customers as is**
-- * Data should be sorted in ascending order by `customer_id`
-- * Output should contain all the fields from `customers`
-- * Make sure to run below provided validation queries and validate the output.

SELECT c.*
FROM orders AS o
	RIGHT OUTER JOIN customers AS c
		ON o.order_customer_id = c.customer_id
WHERE to_char(o.order_date::timestamp, 'yyyy-MM') NOT IN ('2014-01')
ORDER BY 1 ASC;

SELECT count(DISTINCT order_customer_id)
FROM orders
WHERE to_char(order_date, 'yyyy-MM') = '2014-01';

SELECT count(*)
FROM customers;

-- Get the difference
-- Get the count using solution query, both the difference and this count should match

-- * Hint: You can use `NOT IN` or `NOT EXISTS` or `OUTER JOIN` to solve this problem.

-- ### Exercise 3 - Revenue Per Customer

-- Get the revenue generated by each customer for the month of 2014 January
-- * Tables - `orders`, `order_items` and `customers`
-- * Data should be sorted in descending order by revenue and then ascending order by `customer_id`
-- * Output should contain `customer_id`, `customer_fname`, `customer_lname`, `customer_revenue`.
-- * If there are no orders placed by customer, then the corresponding revenue for a given customer should be 0.
-- * Consider only `COMPLETE` and `CLOSED` orders

SELECT c.customer_id, 
		c.customer_fname, 
		c.customer_lname,
		coalesce(round(sum(oi.order_item_subtotal)::numeric, 2),0) AS customer_revenue
	FROM customers AS c
		LEFT OUTER JOIN orders AS o
			ON o.order_customer_id = c.customer_id
				AND to_char(o.order_date, 'yyyy-MM') = '2014-01'
                AND o.order_status IN ('COMPLETE', 'CLOSED')
		LEFT OUTER JOIN order_items AS oi
				ON o.order_id = oi.order_item_order_id 
GROUP BY 1, 2, 3
ORDER BY  4 DESC, c.customer_id ASC;

-- ### Exercise 4 - Revenue Per Category

-- Get the revenue generated for each category for the month of 2014 January
-- * Tables - `orders`, `order_items`, `products` and `categories`
-- * Data should be sorted in ascending order by `category_id`.
-- * Output should contain all the fields from `categories` along with the revenue as `category_revenue`.
-- * Consider only `COMPLETE` and `CLOSED` orders
SELECT c.*,
		coalesce(round(sum(oi.order_item_subtotal)::numeric, 2),0) AS category_revenue
FROM categories AS c
	JOIN products AS p
		ON c.category_id = p.product_category_id
	JOIN order_items AS oi
		ON oi.order_item_product_id = p.product_id
	JOIN orders AS o
		ON o.order_id = oi.order_item_order_id
WHERE to_char(o.order_date, 'yyyy-MM') = '2014-01'
			AND o.order_status IN ('COMPLETE', 'CLOSED')
GROUP BY 1, 2, 3
ORDER BY 4 DESC;

-- ### Exercise 5 - Product Count Per Department

-- Get the count of products for each department.
-- * Tables - `departments`, `categories`, `products`
-- * Data should be sorted in ascending order by `department_id`
-- * Output should contain all the fields from `departments` and the product count as `product_count`
SELECT * FROM departments;

SELECT d.*,
		count(p.*) AS product_count
FROM departments AS d
	JOIN categories AS c
		ON c.category_department_id = d.department_id
	JOIN products AS p
		ON p.product_category_id = c.category_id
GROUP BY 1, 2
ORDER BY 3 DESC;
